CREATE TABLE IF NOT EXISTS words (
    id INT AUTO_INCREMENT PRIMARY KEY,
    word VARCHAR(100) NOT NULL UNIQUE,
    definition TEXT,
    difficulty_level ENUM('Beginner', 'Intermediate', 'Advanced') DEFAULT 'Beginner',
    part_of_speech VARCHAR(50),
    pronunciation VARCHAR(100),
    example_sentence TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS practice_sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    word_id INT NOT NULL,
    user_sentence TEXT NOT NULL,
    score DECIMAL(3,1),
    feedback TEXT,
    corrected_sentence TEXT,
    practiced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (word_id) REFERENCES words(id) ON DELETE CASCADE
);

-- Vocabulary Data with Part of Speech, Pronunciation, and Example Sentences
INSERT INTO words (word, definition, difficulty_level, part_of_speech, pronunciation, example_sentence) VALUES
-- Beginner (50 words)
('Ability', 'The power or skill to do something', 'Beginner', 'Noun', '[a-bil-i-ty]', 'She has the ability to solve complex problems.'),
('Able', 'Having the power or skill to do something', 'Beginner', 'Adjective', '[a-ble]', 'He is able to speak three languages fluently.'),
('About', 'On the subject of; concerning', 'Beginner', 'Preposition', '[a-bout]', 'We talked about the upcoming project.'),
('Above', 'In or to a higher place', 'Beginner', 'Preposition', '[a-bove]', 'The bird flew above the trees.'),
('Accept', 'To agree to receive something', 'Beginner', 'Verb', '[ac-cept]', 'I accept your apology.'),
('Across', 'From one side to the other', 'Beginner', 'Preposition', '[a-cross]', 'We walked across the bridge.'),
('Act', 'To do something; take action', 'Beginner', 'Verb', '[act]', 'You need to act quickly in an emergency.'),
('Action', 'The process of doing something', 'Beginner', 'Noun', '[ac-tion]', 'The government took action to help the homeless.'),
('Add', 'To put something with something else', 'Beginner', 'Verb', '[add]', 'Please add sugar to my coffee.'),
('After', 'Following in time', 'Beginner', 'Preposition', '[af-ter]', 'We went home after the movie.'),
('Again', 'Once more; another time', 'Beginner', 'Adverb', '[a-gain]', 'Can you say that again, please?'),
('Against', 'In opposition to', 'Beginner', 'Preposition', '[a-gainst]', 'They voted against the new policy.'),
('Age', 'The length of time someone has lived', 'Beginner', 'Noun', '[age]', 'What is your age?'),
('Ago', 'Before the present time', 'Beginner', 'Adverb', '[a-go]', 'I met her two years ago.'),
('Agree', 'To have the same opinion', 'Beginner', 'Verb', '[a-gree]', 'I agree with your decision.'),
('Air', 'The invisible gas around Earth', 'Beginner', 'Noun', '[air]', 'The air in the mountains is fresh.'),
('All', 'The whole quantity', 'Beginner', 'Determiner', '[all]', 'All students must attend the meeting.'),
('Allow', 'To give permission', 'Beginner', 'Verb', '[al-low]', 'Parents should allow children to play.'),
('Almost', 'Very nearly', 'Beginner', 'Adverb', '[al-most]', 'I almost missed the bus.'),
('Alone', 'Without anyone else', 'Beginner', 'Adjective', '[a-lone]', 'She likes to work alone.'),
('Along', 'Moving in a constant direction', 'Beginner', 'Preposition', '[a-long]', 'We walked along the river.'),
('Already', 'Before now or before a particular time', 'Beginner', 'Adverb', '[al-read-y]', 'I have already finished my homework.'),
('Also', 'In addition', 'Beginner', 'Adverb', '[al-so]', 'She is smart and also kind.'),
('Always', 'At all times', 'Beginner', 'Adverb', '[al-ways]', 'He always arrives on time.'),
('Among', 'Surrounded by; in the company of', 'Beginner', 'Preposition', '[a-mong]', 'She sat among her friends.'),
('Animal', 'A living organism', 'Beginner', 'Noun', '[an-i-mal]', 'The dog is a loyal animal.'),
('Another', 'One more; an additional', 'Beginner', 'Determiner', '[a-noth-er]', 'Would you like another cup of tea?'),
('Answer', 'A response to a question', 'Beginner', 'Noun', '[an-swer]', 'I don''t know the answer to that question.'),
('Any', 'One or some of something', 'Beginner', 'Determiner', '[an-y]', 'Do you have any questions?'),
('Appear', 'To become visible', 'Beginner', 'Verb', '[ap-pear]', 'Stars appear in the night sky.'),
('Area', 'A region or part of a place', 'Beginner', 'Noun', '[a-re-a]', 'This area is known for its beaches.'),
('Arm', 'The upper limb of the body', 'Beginner', 'Noun', '[arm]', 'He broke his arm playing football.'),
('Around', 'On every side of', 'Beginner', 'Preposition', '[a-round]', 'There are trees around the house.'),
('Ask', 'To say something as a question', 'Beginner', 'Verb', '[ask]', 'She asked me for directions.'),
('Away', 'At a distance from a place', 'Beginner', 'Adverb', '[a-way]', 'The store is only five minutes away.'),
('Baby', 'A very young child', 'Beginner', 'Noun', '[ba-by]', 'The baby is sleeping peacefully.'),
('Back', 'The rear part of something', 'Beginner', 'Noun', '[back]', 'Please sit at the back of the room.'),
('Bad', 'Of poor quality or not good', 'Beginner', 'Adjective', '[bad]', 'The weather was bad yesterday.'),
('Ball', 'A round object used in games', 'Beginner', 'Noun', '[ball]', 'He kicked the ball into the goal.'),
('Be', 'To exist or live', 'Beginner', 'Verb', '[be]', 'I want to be a doctor.'),
('Beautiful', 'Very pleasing to look at', 'Beginner', 'Adjective', '[beau-ti-ful]', 'The sunset was beautiful.'),
('Because', 'For the reason that', 'Beginner', 'Conjunction', '[be-cause]', 'I stayed home because I was sick.'),
('Become', 'To begin to be', 'Beginner', 'Verb', '[be-come]', 'She wants to become a teacher.'),
('Before', 'Earlier than; in front of', 'Beginner', 'Preposition', '[be-fore]', 'Wash your hands before eating.'),
('Begin', 'To start', 'Beginner', 'Verb', '[be-gin]', 'The meeting will begin at 9 AM.'),
('Behind', 'At the back of', 'Beginner', 'Preposition', '[be-hind]', 'The car parked behind the building.'),
('Believe', 'To accept as true', 'Beginner', 'Verb', '[be-lieve]', 'I believe you are right.'),
('Best', 'Of the highest quality', 'Beginner', 'Adjective', '[best]', 'This is the best pizza in town.'),
('Better', 'Of higher quality', 'Beginner', 'Adjective', '[bet-ter]', 'Your English is getting better.'),
('Between', 'In the space separating two things', 'Beginner', 'Preposition', '[be-tween]', 'The park is between the school and the library.'),

-- Intermediate (50 words)
('Abandon', 'To leave completely and finally', 'Intermediate', 'Verb', '[a-ban-don]', 'They had to abandon the burning building.'),
('Absolute', 'Complete and total', 'Intermediate', 'Adjective', '[ab-so-lute]', 'The king had absolute power.'),
('Academic', 'Relating to education or scholarship', 'Intermediate', 'Adjective', '[ac-a-dem-ic]', 'Her academic performance is excellent.'),
('Accomplish', 'To achieve or complete successfully', 'Intermediate', 'Verb', '[ac-com-plish]', 'She accomplished her goal of running a marathon.'),
('Accurate', 'Correct and without errors', 'Intermediate', 'Adjective', '[ac-cu-rate]', 'The weather forecast was accurate.'),
('Achieve', 'To successfully reach a goal', 'Intermediate', 'Verb', '[a-chieve]', 'He achieved his dream of becoming a pilot.'),
('Acknowledge', 'To accept or admit the truth of', 'Intermediate', 'Verb', '[ac-knowl-edge]', 'She acknowledged her mistake.'),
('Acquire', 'To get or obtain something', 'Intermediate', 'Verb', '[ac-quire]', 'He acquired a new skill last year.'),
('Adapt', 'To adjust to new conditions', 'Intermediate', 'Verb', '[a-dapt]', 'Animals adapt to their environment.'),
('Adequate', 'Enough or satisfactory', 'Intermediate', 'Adjective', '[ad-e-quate]', 'We have adequate supplies for the trip.'),
('Adjustment', 'A small change or modification', 'Intermediate', 'Noun', '[ad-just-ment]', 'A small adjustment to the plan is needed.'),
('Admire', 'To respect and look up to', 'Intermediate', 'Verb', '[ad-mire]', 'I admire her dedication to her work.'),
('Admit', 'To confess or acknowledge', 'Intermediate', 'Verb', '[ad-mit]', 'He admitted that he was wrong.'),
('Adopt', 'To take up or start using', 'Intermediate', 'Verb', '[a-dopt]', 'They decided to adopt a new strategy.'),
('Advantage', 'A favorable condition or position', 'Intermediate', 'Noun', '[ad-van-tage]', 'Speaking multiple languages is an advantage.'),
('Adventure', 'An exciting or unusual experience', 'Intermediate', 'Noun', '[ad-ven-ture]', 'Traveling abroad was a great adventure.'),
('Advertise', 'To promote a product or service', 'Intermediate', 'Verb', '[ad-ver-tise]', 'They advertise on social media.'),
('Advice', 'Guidance or recommendations', 'Intermediate', 'Noun', '[ad-vice]', 'She gave me good advice.'),
('Affair', 'An event or matter', 'Intermediate', 'Noun', '[af-fair]', 'The wedding was a grand affair.'),
('Afford', 'To have enough money for', 'Intermediate', 'Verb', '[af-ford]', 'I can''t afford a new car right now.'),
('Afraid', 'Feeling fear', 'Intermediate', 'Adjective', '[a-fraid]', 'She is afraid of spiders.'),
('Aggressive', 'Ready to attack or confront', 'Intermediate', 'Adjective', '[ag-gres-sive]', 'The dog became aggressive when threatened.'),
('Agriculture', 'The practice of farming', 'Intermediate', 'Noun', '[ag-ri-cul-ture]', 'Agriculture is important for the economy.'),
('Alarm', 'A warning of danger', 'Intermediate', 'Noun', '[a-larm]', 'The fire alarm went off at midnight.'),
('Alternative', 'Another choice or option', 'Intermediate', 'Noun', '[al-ter-na-tive]', 'We need to find an alternative solution.'),
('Ambition', 'A strong desire to succeed', 'Intermediate', 'Noun', '[am-bi-tion]', 'His ambition is to become a CEO.'),
('Ambitious', 'Having a strong desire to succeed', 'Intermediate', 'Adjective', '[am-bi-tious]', 'She is an ambitious young professional.'),
('Amuse', 'To make someone laugh or smile', 'Intermediate', 'Verb', '[a-muse]', 'The clown amused the children.'),
('Analyze', 'To examine in detail', 'Intermediate', 'Verb', '[an-a-lyze]', 'Scientists analyze data carefully.'),
('Ancient', 'Very old; from long ago', 'Intermediate', 'Adjective', '[an-cient]', 'The ancient ruins attract many tourists.'),
('Anger', 'A strong feeling of displeasure', 'Intermediate', 'Noun', '[an-ger]', 'He tried to control his anger.'),
('Announce', 'To make a public statement', 'Intermediate', 'Verb', '[an-nounce]', 'They will announce the winner tomorrow.'),
('Annoy', 'To irritate someone', 'Intermediate', 'Verb', '[an-noy]', 'Loud music annoys the neighbors.'),
('Annual', 'Happening once every year', 'Intermediate', 'Adjective', '[an-nu-al]', 'The company holds an annual meeting.'),
('Anticipate', 'To expect or predict', 'Intermediate', 'Verb', '[an-ti-ci-pate]', 'We anticipate a busy holiday season.'),
('Anxiety', 'A feeling of worry or nervousness', 'Intermediate', 'Noun', '[anx-i-e-ty]', 'She experiences anxiety before exams.'),
('Apologize', 'To say sorry for something', 'Intermediate', 'Verb', '[a-pol-o-gize]', 'He apologized for being late.'),
('Apparent', 'Clearly visible or obvious', 'Intermediate', 'Adjective', '[ap-par-ent]', 'It was apparent that she was upset.'),
('Appeal', 'To make a serious request', 'Intermediate', 'Verb', '[ap-peal]', 'The charity made an appeal for donations.'),
('Appetite', 'A desire for food', 'Intermediate', 'Noun', '[ap-pe-tite]', 'Exercise increases your appetite.'),
('Apply', 'To make a formal request', 'Intermediate', 'Verb', '[ap-ply]', 'She decided to apply for the job.'),
('Appreciate', 'To recognize the value of something', 'Intermediate', 'Verb', '[ap-pre-ci-ate]', 'I appreciate your help.'),
('Approach', 'To come near or closer to', 'Intermediate', 'Verb', '[ap-proach]', 'The deadline is approaching fast.'),
('Appropriate', 'Suitable or proper', 'Intermediate', 'Adjective', '[ap-pro-pri-ate]', 'Wear appropriate clothing for the interview.'),
('Approve', 'To agree to or accept', 'Intermediate', 'Verb', '[ap-prove]', 'The manager approved the request.'),
('Argue', 'To exchange opposing views', 'Intermediate', 'Verb', '[ar-gue]', 'They often argue about politics.'),
('Arrange', 'To organize or put in order', 'Intermediate', 'Verb', '[ar-range]', 'She arranged the flowers beautifully.'),
('Arrest', 'To take someone into custody', 'Intermediate', 'Verb', '[ar-rest]', 'The police arrested the suspect.'),
('Article', 'A piece of writing in a publication', 'Intermediate', 'Noun', '[ar-ti-cle]', 'I read an interesting article today.'),
('Artificial', 'Made by humans, not natural', 'Intermediate', 'Adjective', '[ar-ti-fi-cial]', 'Artificial flowers look real.'),

-- Advanced (50 words)
('Aberration', 'A departure from what is normal', 'Advanced', 'Noun', '[ab-er-ra-tion]', 'His behavior was an aberration from his usual calm demeanor.'),
('Abhor', 'To regard with disgust and hatred', 'Advanced', 'Verb', '[ab-hor]', 'I abhor violence of any kind.'),
('Acquiesce', 'To accept reluctantly without protest', 'Advanced', 'Verb', '[ac-qui-esce]', 'She acquiesced to her parents'' wishes.'),
('Alacrity', 'Brisk and cheerful readiness', 'Advanced', 'Noun', '[a-lac-ri-ty]', 'He accepted the challenge with alacrity.'),
('Ameliorate', 'To make something better', 'Advanced', 'Verb', '[a-me-lio-rate]', 'The government tried to ameliorate the housing crisis.'),
('Amiable', 'Friendly and pleasant', 'Advanced', 'Adjective', '[a-mi-a-ble]', 'She has an amiable personality.'),
('Appease', 'To calm someone by giving them what they want', 'Advanced', 'Verb', '[ap-pease]', 'He tried to appease the angry customer.'),
('Arcane', 'Mysterious and known by few', 'Advanced', 'Adjective', '[ar-cane]', 'The book contained arcane knowledge.'),
('Avarice', 'Extreme greed for wealth', 'Advanced', 'Noun', '[av-a-rice]', 'His avarice led to his downfall.'),
('Benevolent', 'Kind and generous', 'Advanced', 'Adjective', '[be-nev-o-lent]', 'The benevolent donor gave millions to charity.'),
('Brazen', 'Bold and without shame', 'Advanced', 'Adjective', '[bra-zen]', 'It was a brazen lie.'),
('Brusque', 'Abrupt in speech or manner', 'Advanced', 'Adjective', '[brusque]', 'His brusque response surprised everyone.'),
('Cajole', 'To persuade with flattery', 'Advanced', 'Verb', '[ca-jole]', 'She cajoled him into helping her.'),
('Callous', 'Showing cruel disregard for others', 'Advanced', 'Adjective', '[cal-lous]', 'His callous remarks hurt her deeply.'),
('Candor', 'Openness and honesty', 'Advanced', 'Noun', '[can-dor]', 'I appreciate your candor.'),
('Capricious', 'Changing mood unpredictably', 'Advanced', 'Adjective', '[ca-pri-cious]', 'The capricious weather made planning difficult.'),
('Chide', 'To scold or rebuke', 'Advanced', 'Verb', '[chide]', 'The teacher chided the student for being late.'),
('Circumspect', 'Wary and careful', 'Advanced', 'Adjective', '[cir-cum-spect]', 'Be circumspect when making important decisions.'),
('Clandestine', 'Kept secret, especially illicit', 'Advanced', 'Adjective', '[clan-des-tine]', 'They held clandestine meetings at night.'),
('Coerce', 'To force someone to do something', 'Advanced', 'Verb', '[co-erce]', 'He was coerced into signing the document.'),
('Coherent', 'Logical and consistent', 'Advanced', 'Adjective', '[co-her-ent]', 'She gave a coherent explanation of the problem.'),
('Complacency', 'Smug self-satisfaction', 'Advanced', 'Noun', '[com-pla-cen-cy]', 'Complacency can lead to failure.'),
('Condescending', 'Acting superior to others', 'Advanced', 'Adjective', '[con-de-scend-ing]', 'His condescending tone annoyed everyone.'),
('Connive', 'To conspire secretly', 'Advanced', 'Verb', '[con-nive]', 'They connived to steal the money.'),
('Debilitate', 'To make weak', 'Advanced', 'Verb', '[de-bil-i-tate]', 'The illness debilitated him for months.'),
('Decry', 'To publicly denounce', 'Advanced', 'Verb', '[de-cry]', 'Critics decried the new policy.'),
('Deference', 'Humble submission and respect', 'Advanced', 'Noun', '[def-er-ence]', 'She showed deference to her elders.'),
('Demure', 'Reserved and modest', 'Advanced', 'Adjective', '[de-mure]', 'She gave a demure smile.'),
('Deride', 'To ridicule or mock', 'Advanced', 'Verb', '[de-ride]', 'Critics derided his artistic choices.'),
('Diligent', 'Hardworking and careful', 'Advanced', 'Adjective', '[dil-i-gent]', 'She is a diligent student.'),
('Discern', 'To perceive or recognize', 'Advanced', 'Verb', '[dis-cern]', 'It was difficult to discern the truth.'),
('Disdain', 'Contempt or scorn', 'Advanced', 'Noun', '[dis-dain]', 'She looked at him with disdain.'),
('Eloquent', 'Fluent and persuasive in speaking', 'Advanced', 'Adjective', '[el-o-quent]', 'He gave an eloquent speech.'),
('Empathy', 'Understanding others'' feelings', 'Advanced', 'Noun', '[em-pa-thy]', 'Empathy is important in relationships.'),
('Enigma', 'Something mysterious or puzzling', 'Advanced', 'Noun', '[e-nig-ma]', 'Her behavior remains an enigma.'),
('Ephemeral', 'Lasting for a very short time', 'Advanced', 'Adjective', '[e-phem-er-al]', 'Fame can be ephemeral.'),
('Erudite', 'Having great knowledge', 'Advanced', 'Adjective', '[er-u-dite]', 'The professor is an erudite scholar.'),
('Exacerbate', 'To make worse', 'Advanced', 'Verb', '[ex-ac-er-bate]', 'His comments exacerbated the situation.'),
('Extol', 'To praise enthusiastically', 'Advanced', 'Verb', '[ex-tol]', 'She extolled the virtues of hard work.'),
('Fastidious', 'Very attentive to detail', 'Advanced', 'Adjective', '[fas-tid-i-ous]', 'He is fastidious about cleanliness.'),
('Furtive', 'Attempting to avoid notice', 'Advanced', 'Adjective', '[fur-tive]', 'She gave a furtive glance around the room.'),
('Gratuitous', 'Uncalled for or unnecessary', 'Advanced', 'Adjective', '[gra-tu-i-tous]', 'The movie had gratuitous violence.'),
('Haughty', 'Arrogantly superior', 'Advanced', 'Adjective', '[haugh-ty]', 'Her haughty attitude alienated her colleagues.'),
('Hypocrisy', 'Claiming beliefs one doesn''t have', 'Advanced', 'Noun', '[hy-poc-ri-sy]', 'His hypocrisy was revealed.'),
('Impeccable', 'Faultless and perfect', 'Advanced', 'Adjective', '[im-pec-ca-ble]', 'His English is impeccable.'),
('Impertinent', 'Not showing proper respect', 'Advanced', 'Adjective', '[im-per-ti-nent]', 'That was an impertinent remark.'),
('Ineffable', 'Too great to be expressed in words', 'Advanced', 'Adjective', '[in-ef-fa-ble]', 'She felt ineffable joy.'),
('Insidious', 'Proceeding harmfully in a subtle way', 'Advanced', 'Adjective', '[in-sid-i-ous]', 'The disease has an insidious onset.'),
('Meticulous', 'Showing great attention to detail', 'Advanced', 'Adjective', '[me-tic-u-lous]', 'She is meticulous in her work.'),
('Serendipity', 'Finding good things by chance', 'Advanced', 'Noun', '[ser-en-dip-i-ty]', 'Meeting her was pure serendipity.');
