CREATE TABLE IF NOT EXISTS words (
    id INT AUTO_INCREMENT PRIMARY KEY,
    word VARCHAR(100) NOT NULL UNIQUE,
    definition TEXT,
    difficulty_level ENUM('Beginner', 'Intermediate', 'Advanced') DEFAULT 'Beginner',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS practice_sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    word_id INT NOT NULL,
    user_sentence TEXT NOT NULL,
    score DECIMAL(3,1),
    feedback TEXT,
    corrected_sentence TEXT,
    practiced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (word_id) REFERENCES words(id) ON DELETE CASCADE
);

-- คำศัพท์ในระบบนะจ๊ะ อิอิ
INSERT INTO words (word, definition, difficulty_level) VALUES
-- Beginner
('swatdeekub', 'Hello in Thai', 'Beginner'),
('ability', 'The physical or mental power or skill needed to do something', 'Beginner'),
('able', 'Having the power, skill, means, or opportunity to do something', 'Beginner'),
('about', 'On the subject of; concerning', 'Beginner'),
('above', 'In or to a higher place or position than something else', 'Beginner'),
('accept', 'To agree to take something', 'Beginner'),
('according', 'As stated by or in', 'Beginner'),
('account', 'A report or description of an event or experience', 'Beginner'),
('across', 'From one side to the other of something', 'Beginner'),
('act', 'To take action; do something', 'Beginner'),
('action', 'The fact or process of doing something', 'Beginner'),
('activity', 'The condition in which things are happening or being done', 'Beginner'),
('actually', 'As the truth or facts of a situation', 'Beginner'),
('add', 'To put something with something else', 'Beginner'),
('address', 'The particulars of the place where someone lives or an organization is situated', 'Beginner'),
('adult', 'A person who is fully grown or developed', 'Beginner'),
('affect', 'To have an effect on; make a difference to', 'Beginner'),
('after', 'In the time following (an event or another period of time)', 'Beginner'),
('again', 'Another time; once more', 'Beginner'),
('against', 'In opposition to', 'Beginner'),
('age', 'The length of time that a person has lived or a thing has existed', 'Beginner'),
('agency', 'A business or organization established to provide a particular service', 'Beginner'),
('agent', 'A person who acts on behalf of another person or group', 'Beginner'),
('ago', 'Before the present time', 'Beginner'),
('agree', 'To have the same opinion about something', 'Beginner'),
('agreement', 'Harmony or accordance in opinion or feeling', 'Beginner'),
('ahead', 'Further forward in space; in the line of one''s forward motion', 'Beginner'),
('air', 'The invisible gaseous substance surrounding the earth', 'Beginner'),
('all', 'The whole quantity or extent of a particular group or thing', 'Beginner'),
('allow', 'To give (someone) permission to do something', 'Beginner'),
('almost', 'Not quite; very nearly', 'Beginner'),
('alone', 'Having no one else present', 'Beginner'),
('along', 'Moving in a constant direction on (a road, path, or any more or less horizontal surface)', 'Beginner'),
('already', 'Before or by now or the time in question', 'Beginner'),
('also', 'In addition; too', 'Beginner'),
('although', 'In spite of the fact that; even though', 'Beginner'),
('always', 'At all times; on all occasions', 'Beginner'),
('American', 'Relating to or characteristic of the United States or its inhabitants', 'Beginner'),
('among', 'Surrounded by; in the company of', 'Beginner'),
('amount', 'A quantity of something, especially the total of a thing or things in number, size, value, or extent', 'Beginner'),
('analysis', 'Detailed examination of the elements or structure of something', 'Beginner'),
('and', 'Used to connect words of the same part of speech, clauses, or sentences, that are to be taken jointly', 'Beginner'),
('animal', 'A living organism that feeds on organic matter', 'Beginner'),
('another', 'Used to refer to an additional person or thing of the same type as one already mentioned or known', 'Beginner'),
('answer', 'A thing said, written, or done to deal with or as a reaction to a question, statement, or situation', 'Beginner'),
('any', 'Used to refer to one or some of a thing or number of things, no matter how much or how many', 'Beginner'),
('anyone', 'Any person or people', 'Beginner'),
('anything', 'Used to refer to a thing, no matter what', 'Beginner'),
('appear', 'To come into sight; become visible', 'Beginner'),
('apply', 'To make a formal application or request', 'Beginner'),

-- Intermediate
('abandon', 'To leave a place, thing, or person, usually for ever', 'Intermediate'),
('absolute', 'Not mixed or adulterated; pure', 'Intermediate'),
('academic', 'Relating to education and scholarship', 'Intermediate'),
('acceptable', 'Able to be agreed on; suitable', 'Intermediate'),
('accompany', 'To go somewhere with (someone) as a companion or escort', 'Intermediate'),
('accountant', 'A person whose job is to keep or inspect financial accounts', 'Intermediate'),
('accurate', 'Correct in all details; exact', 'Intermediate'),
('accuse', 'To charge (someone) with an offense or crime', 'Intermediate'),
('acknowledge', 'To accept or admit the existence or truth of', 'Intermediate'),
('acquire', 'To buy or obtain (an asset or object) for oneself', 'Intermediate'),
('adapt', 'To make (something) suitable for a new use or purpose; modify', 'Intermediate'),
('adequate', 'Satisfactory or acceptable in quality or quantity', 'Intermediate'),
('adjustment', 'A small alteration or movement made to achieve a desired fit, appearance, or result', 'Intermediate'),
('admiration', 'Respect and warm approval', 'Intermediate'),
('admit', 'To confess to be true or to be the case', 'Intermediate'),
('adolescent', 'A young person developing into an adult', 'Intermediate'),
('adopt', 'To choose to take up or follow (an idea, method, or course of action)', 'Intermediate'),
('advanced', 'Far on or ahead in development or progress', 'Intermediate'),
('advantage', 'A condition or circumstance that puts one in a favorable or superior position', 'Intermediate'),
('adventure', 'An unusual and exciting, typically hazardous, experience or activity', 'Intermediate'),
('advise', 'To offer suggestions about the best course of action to someone', 'Intermediate'),
('affair', 'An event or sequence of events of a specified kind or that has previously been referred to', 'Intermediate'),
('affection', 'A gentle feeling of fondness or liking', 'Intermediate'),
('afford', 'To have enough money to pay for', 'Intermediate'),
('afraid', 'Feeling fear or anxiety; frightened', 'Intermediate'),
('agriculture', 'The science or practice of farming', 'Intermediate'),
('aircraft', 'An airplane, helicopter, or other machine capable of flight', 'Intermediate'),
('alarm', 'An anxious awareness of danger', 'Intermediate'),
('alcohol', 'A colorless volatile flammable liquid which is the intoxicating constituent of wine, beer, spirits, and other drinks', 'Intermediate'),

('ambitious', 'Having or showing a strong desire and determination to succeed', 'Intermediate'),
('amuse', 'To cause (someone) to find something funny', 'Intermediate'),
('analyze', 'To examine methodically and in detail the constitution or structure of', 'Intermediate'),
('ancient', 'Belonging to the very distant past and no longer in existence', 'Intermediate'),
('anger', 'A strong feeling of annoyance, displeasure, or hostility', 'Intermediate'),
('angle', 'The space (usually measured in degrees) between two intersecting lines or surfaces at or close to the point where they meet', 'Intermediate'),
('anniversary', 'The date on which an event took place in a previous year', 'Intermediate'),
('announce', 'To make a public and typically formal declaration about a fact, occurrence, or intention', 'Intermediate'),
('annoy', 'To irritate (someone); make (someone) a little angry', 'Intermediate'),
('annual', 'Occurring once every year', 'Intermediate'),
('anticipate', 'To regard as probable; expect or predict', 'Intermediate'),
('anxiety', 'A feeling of worry, nervousness, or unease', 'Intermediate'),
('anxious', 'Experiencing worry, unease, or nervousness', 'Intermediate'),
('apart', 'Separated by a distance; at a specified distance from each other in time or space', 'Intermediate'),
('apologize', 'To express regret for something that one has done wrong', 'Intermediate'),
('apparent', 'Clearly visible or understood; obvious', 'Intermediate'),
('appeal', 'To make a serious or urgent request, typically to the public', 'Intermediate'),
('appetite', 'A natural desire to satisfy a bodily need, especially for food', 'Intermediate'),
('appoint', 'To assign a job or role to (someone)', 'Intermediate'),

-- Advanced
('aberration', 'A departure from what is normal, usual, or expected, typically one that is unwelcome', 'Advanced'),
('abhor', 'To regard with disgust and hatred', 'Advanced'),
('acquiesce', 'To accept something reluctantly but without protest', 'Advanced'),
('alacrity', 'Brisk and cheerful readiness', 'Advanced'),
('amiable', 'Having or displaying a friendly and pleasant manner', 'Advanced'),
('appease', 'To pacify or placate (someone) by acceding to their demands', 'Advanced'),
('arcane', 'Understood by few; mysterious or secret', 'Advanced'),
('avarice', 'Extreme greed for wealth or material gain', 'Advanced'),
('brazen', 'Bold and without shame', 'Advanced'),
('brusque', 'Abrupt or offhand in speech or manner', 'Advanced'),
('cajole', 'To persuade someone to do something by sustained coaxing or flattery', 'Advanced'),
('callous', 'Showing or having an insensitive and cruel disregard for others', 'Advanced'),
('candor', 'The quality of being open and honest in expression; frankness', 'Advanced'),
('chide', 'To scold or rebuke', 'Advanced'),
('circumspect', 'Wary and unwilling to take risks', 'Advanced'),
('clandestine', 'Kept secret or done secretively, especially because illicit', 'Advanced'),
('coerce', 'To persuade (an unwilling person) to do something by using force or threats', 'Advanced'),
('coherent', '(of an argument, theory, or policy) logical and consistent', 'Advanced'),
('complacency', 'A feeling of smug or uncritical satisfaction with oneself or one''s achievements', 'Advanced'),
('confidant', 'A person with whom one shares a secret or private matter, trusting them not to repeat it to others', 'Advanced'),
('connive', 'To conspiratorially secret to do something immoral, illegal, or harmful', 'Advanced'),
('cumulative', 'Increasing or increased in quantity, degree, or force by successive additions', 'Advanced'),
('debase', 'To reduce (something) in quality or value; degrade', 'Advanced'),
('decry', 'To publicly denounce', 'Advanced'),
('deferance', 'Humble submission and respect', 'Advanced'),
('demure', '(of a woman or her behavior) reserved, modest, and shy', 'Advanced'),
('deride', 'To express contempt for; ridicule', 'Advanced'),
('despot', 'A ruler or other person who holds absolute power, typically one who exercises it in a cruel or oppressive way', 'Advanced'),
('diligent', 'Having or showing care and conscientiousness in one''s work or duties', 'Advanced'),
('elated', 'Ecstatically happy', 'Advanced'),
('eloquent', 'Fluent or persuasive in speaking or writing', 'Advanced'),
('embezzle', 'To steal or misappropriate (money placed in one''s trust or belonging to the organization for which one works)', 'Advanced'),
('empathy', 'The ability to understand and share the feelings of another', 'Advanced'),
('enmity', 'The state or feeling of being actively opposed or hostile to someone or something', 'Advanced'),
('erudite', 'Having or showing great knowledge or learning', 'Advanced'),
('extol', 'To praise enthusiastically', 'Advanced'),
('fabricate', 'To invent or concoct (something), typically with deceitful intent', 'Advanced'),
('feral', '(especially of an animal) in a wild state, especially after escape from captivity or domestication', 'Advanced'),
('flabbergasted', 'Greatly surprised; astonished', 'Advanced'),
('forsake', 'To abandon (someone or something)', 'Advanced'),
('fractious', '(typically of children) irritable and quarrelsome', 'Advanced'),
('furtive', 'Attempting to avoid notice or attention, typically because of guilt or a belief that discovery would lead to trouble; secretive', 'Advanced'),
('gluttony', 'Habitual greed or excess in eating', 'Advanced'),
('gratuitous', 'Uncalled for; lacking good reason; unwarranted', 'Advanced'),
('haughty', 'Arrogantly superior and disdainful', 'Advanced'),
('hypocrisy', 'The practice of claiming to have higher standards or more noble beliefs than is the case', 'Advanced'),
('impeccable', '(of behavior, performance, or appearance) in accordance with the highest standards of propriety; faultless', 'Advanced'),
('impertinent', 'Not showing proper respect; rude', 'Advanced'),
('implacable', 'Unable to be placated', 'Advanced'),
('serendipity', 'Finding something good without looking for it', 'Advanced');
