CREATE TABLE IF NOT EXISTS words (
    id INT AUTO_INCREMENT PRIMARY KEY,
    word VARCHAR(100) NOT NULL UNIQUE,
    definition TEXT,
    difficulty_level ENUM('Beginner', 'Intermediate', 'Advanced') DEFAULT 'Beginner',
    part_of_speech VARCHAR(50),
    pronunciation VARCHAR(100),
    example_sentence TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS practice_sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    word_id INT NOT NULL,
    user_sentence TEXT NOT NULL,
    score DECIMAL(3,1),
    feedback TEXT,
    corrected_sentence TEXT,
    practiced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (word_id) REFERENCES words(id) ON DELETE CASCADE
);

-- Vocabulary Data with Part of Speech, Pronunciation, and Example Sentences
INSERT INTO words (word, definition, difficulty_level, part_of_speech, pronunciation, example_sentence) VALUES
-- Beginner (50 words)
('ability', 'The power or skill to do something', 'Beginner', 'noun', '/əˈbɪl.ə.ti/', 'She has the ability to solve complex problems.'),
('able', 'Having the power or skill to do something', 'Beginner', 'adjective', '/ˈeɪ.bəl/', 'He is able to speak three languages fluently.'),
('about', 'On the subject of; concerning', 'Beginner', 'preposition', '/əˈbaʊt/', 'We talked about the upcoming project.'),
('above', 'In or to a higher place', 'Beginner', 'preposition', '/əˈbʌv/', 'The bird flew above the trees.'),
('accept', 'To agree to receive something', 'Beginner', 'verb', '/əkˈsept/', 'I accept your apology.'),
('across', 'From one side to the other', 'Beginner', 'preposition', '/əˈkrɒs/', 'We walked across the bridge.'),
('act', 'To do something; take action', 'Beginner', 'verb', '/ækt/', 'You need to act quickly in an emergency.'),
('action', 'The process of doing something', 'Beginner', 'noun', '/ˈæk.ʃən/', 'The government took action to help the homeless.'),
('add', 'To put something with something else', 'Beginner', 'verb', '/æd/', 'Please add sugar to my coffee.'),
('after', 'Following in time', 'Beginner', 'preposition', '/ˈɑːf.tər/', 'We went home after the movie.'),
('again', 'Once more; another time', 'Beginner', 'adverb', '/əˈɡen/', 'Can you say that again, please?'),
('against', 'In opposition to', 'Beginner', 'preposition', '/əˈɡenst/', 'They voted against the new policy.'),
('age', 'The length of time someone has lived', 'Beginner', 'noun', '/eɪdʒ/', 'What is your age?'),
('ago', 'Before the present time', 'Beginner', 'adverb', '/əˈɡəʊ/', 'I met her two years ago.'),
('agree', 'To have the same opinion', 'Beginner', 'verb', '/əˈɡriː/', 'I agree with your decision.'),
('air', 'The invisible gas around Earth', 'Beginner', 'noun', '/eər/', 'The air in the mountains is fresh.'),
('all', 'The whole quantity', 'Beginner', 'determiner', '/ɔːl/', 'All students must attend the meeting.'),
('allow', 'To give permission', 'Beginner', 'verb', '/əˈlaʊ/', 'Parents should allow children to play.'),
('almost', 'Very nearly', 'Beginner', 'adverb', '/ˈɔːl.məʊst/', 'I almost missed the bus.'),
('alone', 'Without anyone else', 'Beginner', 'adjective', '/əˈləʊn/', 'She likes to work alone.'),
('along', 'Moving in a constant direction', 'Beginner', 'preposition', '/əˈlɒŋ/', 'We walked along the river.'),
('already', 'Before now or before a particular time', 'Beginner', 'adverb', '/ɔːlˈred.i/', 'I have already finished my homework.'),
('also', 'In addition', 'Beginner', 'adverb', '/ˈɔːl.səʊ/', 'She is smart and also kind.'),
('always', 'At all times', 'Beginner', 'adverb', '/ˈɔːl.weɪz/', 'He always arrives on time.'),
('among', 'Surrounded by; in the company of', 'Beginner', 'preposition', '/əˈmʌŋ/', 'She sat among her friends.'),
('animal', 'A living organism', 'Beginner', 'noun', '/ˈæn.ɪ.məl/', 'The dog is a loyal animal.'),
('another', 'One more; an additional', 'Beginner', 'determiner', '/əˈnʌð.ər/', 'Would you like another cup of tea?'),
('answer', 'A response to a question', 'Beginner', 'noun', '/ˈɑːn.sər/', 'I don''t know the answer to that question.'),
('any', 'One or some of something', 'Beginner', 'determiner', '/ˈen.i/', 'Do you have any questions?'),
('appear', 'To become visible', 'Beginner', 'verb', '/əˈpɪər/', 'Stars appear in the night sky.'),
('area', 'A region or part of a place', 'Beginner', 'noun', '/ˈeə.ri.ə/', 'This area is known for its beaches.'),
('arm', 'The upper limb of the body', 'Beginner', 'noun', '/ɑːm/', 'He broke his arm playing football.'),
('around', 'On every side of', 'Beginner', 'preposition', '/əˈraʊnd/', 'There are trees around the house.'),
('ask', 'To say something as a question', 'Beginner', 'verb', '/ɑːsk/', 'She asked me for directions.'),
('away', 'At a distance from a place', 'Beginner', 'adverb', '/əˈweɪ/', 'The store is only five minutes away.'),
('baby', 'A very young child', 'Beginner', 'noun', '/ˈbeɪ.bi/', 'The baby is sleeping peacefully.'),
('back', 'The rear part of something', 'Beginner', 'noun', '/bæk/', 'Please sit at the back of the room.'),
('bad', 'Of poor quality or not good', 'Beginner', 'adjective', '/bæd/', 'The weather was bad yesterday.'),
('ball', 'A round object used in games', 'Beginner', 'noun', '/bɔːl/', 'He kicked the ball into the goal.'),
('be', 'To exist or live', 'Beginner', 'verb', '/biː/', 'I want to be a doctor.'),
('beautiful', 'Very pleasing to look at', 'Beginner', 'adjective', '/ˈbjuː.tɪ.fəl/', 'The sunset was beautiful.'),
('because', 'For the reason that', 'Beginner', 'conjunction', '/bɪˈkɒz/', 'I stayed home because I was sick.'),
('become', 'To begin to be', 'Beginner', 'verb', '/bɪˈkʌm/', 'She wants to become a teacher.'),
('before', 'Earlier than; in front of', 'Beginner', 'preposition', '/bɪˈfɔːr/', 'Wash your hands before eating.'),
('begin', 'To start', 'Beginner', 'verb', '/bɪˈɡɪn/', 'The meeting will begin at 9 AM.'),
('behind', 'At the back of', 'Beginner', 'preposition', '/bɪˈhaɪnd/', 'The car parked behind the building.'),
('believe', 'To accept as true', 'Beginner', 'verb', '/bɪˈliːv/', 'I believe you are right.'),
('best', 'Of the highest quality', 'Beginner', 'adjective', '/best/', 'This is the best pizza in town.'),
('better', 'Of higher quality', 'Beginner', 'adjective', '/ˈbet.ər/', 'Your English is getting better.'),
('between', 'In the space separating two things', 'Beginner', 'preposition', '/bɪˈtwiːn/', 'The park is between the school and the library.'),

-- Intermediate (50 words)
('abandon', 'To leave completely and finally', 'Intermediate', 'verb', '/əˈbæn.dən/', 'They had to abandon the burning building.'),
('absolute', 'Complete and total', 'Intermediate', 'adjective', '/ˈæb.sə.luːt/', 'The king had absolute power.'),
('academic', 'Relating to education or scholarship', 'Intermediate', 'adjective', '/ˌæk.əˈdem.ɪk/', 'Her academic performance is excellent.'),
('accomplish', 'To achieve or complete successfully', 'Intermediate', 'verb', '/əˈkʌm.plɪʃ/', 'She accomplished her goal of running a marathon.'),
('accurate', 'Correct and without errors', 'Intermediate', 'adjective', '/ˈæk.jə.rət/', 'The weather forecast was accurate.'),
('achieve', 'To successfully reach a goal', 'Intermediate', 'verb', '/əˈtʃiːv/', 'He achieved his dream of becoming a pilot.'),
('acknowledge', 'To accept or admit the truth of', 'Intermediate', 'verb', '/əkˈnɒl.ɪdʒ/', 'She acknowledged her mistake.'),
('acquire', 'To get or obtain something', 'Intermediate', 'verb', '/əˈkwaɪər/', 'He acquired a new skill last year.'),
('adapt', 'To adjust to new conditions', 'Intermediate', 'verb', '/əˈdæpt/', 'Animals adapt to their environment.'),
('adequate', 'Enough or satisfactory', 'Intermediate', 'adjective', '/ˈæd.ə.kwət/', 'We have adequate supplies for the trip.'),
('adjustment', 'A small change or modification', 'Intermediate', 'noun', '/əˈdʒʌst.mənt/', 'A small adjustment to the plan is needed.'),
('admire', 'To respect and look up to', 'Intermediate', 'verb', '/ədˈmaɪər/', 'I admire her dedication to her work.'),
('admit', 'To confess or acknowledge', 'Intermediate', 'verb', '/ədˈmɪt/', 'He admitted that he was wrong.'),
('adopt', 'To take up or start using', 'Intermediate', 'verb', '/əˈdɒpt/', 'They decided to adopt a new strategy.'),
('advantage', 'A favorable condition or position', 'Intermediate', 'noun', '/ədˈvɑːn.tɪdʒ/', 'Speaking multiple languages is an advantage.'),
('adventure', 'An exciting or unusual experience', 'Intermediate', 'noun', '/ədˈven.tʃər/', 'Traveling abroad was a great adventure.'),
('advertise', 'To promote a product or service', 'Intermediate', 'verb', '/ˈæd.və.taɪz/', 'They advertise on social media.'),
('advice', 'Guidance or recommendations', 'Intermediate', 'noun', '/ədˈvaɪs/', 'She gave me good advice.'),
('affair', 'An event or matter', 'Intermediate', 'noun', '/əˈfeər/', 'The wedding was a grand affair.'),
('afford', 'To have enough money for', 'Intermediate', 'verb', '/əˈfɔːd/', 'I can''t afford a new car right now.'),
('afraid', 'Feeling fear', 'Intermediate', 'adjective', '/əˈfreɪd/', 'She is afraid of spiders.'),
('aggressive', 'Ready to attack or confront', 'Intermediate', 'adjective', '/əˈɡres.ɪv/', 'The dog became aggressive when threatened.'),
('agriculture', 'The practice of farming', 'Intermediate', 'noun', '/ˈæɡ.rɪ.kʌl.tʃər/', 'Agriculture is important for the economy.'),
('alarm', 'A warning of danger', 'Intermediate', 'noun', '/əˈlɑːm/', 'The fire alarm went off at midnight.'),
('alternative', 'Another choice or option', 'Intermediate', 'noun', '/ɔːlˈtɜː.nə.tɪv/', 'We need to find an alternative solution.'),
('ambition', 'A strong desire to succeed', 'Intermediate', 'noun', '/æmˈbɪʃ.ən/', 'His ambition is to become a CEO.'),
('ambitious', 'Having a strong desire to succeed', 'Intermediate', 'adjective', '/æmˈbɪʃ.əs/', 'She is an ambitious young professional.'),
('amuse', 'To make someone laugh or smile', 'Intermediate', 'verb', '/əˈmjuːz/', 'The clown amused the children.'),
('analyze', 'To examine in detail', 'Intermediate', 'verb', '/ˈæn.əl.aɪz/', 'Scientists analyze data carefully.'),
('ancient', 'Very old; from long ago', 'Intermediate', 'adjective', '/ˈeɪn.ʃənt/', 'The ancient ruins attract many tourists.'),
('anger', 'A strong feeling of displeasure', 'Intermediate', 'noun', '/ˈæŋ.ɡər/', 'He tried to control his anger.'),
('announce', 'To make a public statement', 'Intermediate', 'verb', '/əˈnaʊns/', 'They will announce the winner tomorrow.'),
('annoy', 'To irritate someone', 'Intermediate', 'verb', '/əˈnɔɪ/', 'Loud music annoys the neighbors.'),
('annual', 'Happening once every year', 'Intermediate', 'adjective', '/ˈæn.ju.əl/', 'The company holds an annual meeting.'),
('anticipate', 'To expect or predict', 'Intermediate', 'verb', '/ænˈtɪs.ɪ.peɪt/', 'We anticipate a busy holiday season.'),
('anxiety', 'A feeling of worry or nervousness', 'Intermediate', 'noun', '/æŋˈzaɪ.ə.ti/', 'She experiences anxiety before exams.'),
('apologize', 'To say sorry for something', 'Intermediate', 'verb', '/əˈpɒl.ə.dʒaɪz/', 'He apologized for being late.'),
('apparent', 'Clearly visible or obvious', 'Intermediate', 'adjective', '/əˈpær.ənt/', 'It was apparent that she was upset.'),
('appeal', 'To make a serious request', 'Intermediate', 'verb', '/əˈpiːl/', 'The charity made an appeal for donations.'),
('appetite', 'A desire for food', 'Intermediate', 'noun', '/ˈæp.ə.taɪt/', 'Exercise increases your appetite.'),
('apply', 'To make a formal request', 'Intermediate', 'verb', '/əˈplaɪ/', 'She decided to apply for the job.'),
('appreciate', 'To recognize the value of something', 'Intermediate', 'verb', '/əˈpriː.ʃi.eɪt/', 'I appreciate your help.'),
('approach', 'To come near or closer to', 'Intermediate', 'verb', '/əˈprəʊtʃ/', 'The deadline is approaching fast.'),
('appropriate', 'Suitable or proper', 'Intermediate', 'adjective', '/əˈprəʊ.pri.ət/', 'Wear appropriate clothing for the interview.'),
('approve', 'To agree to or accept', 'Intermediate', 'verb', '/əˈpruːv/', 'The manager approved the request.'),
('argue', 'To exchange opposing views', 'Intermediate', 'verb', '/ˈɑːɡ.juː/', 'They often argue about politics.'),
('arrange', 'To organize or put in order', 'Intermediate', 'verb', '/əˈreɪndʒ/', 'She arranged the flowers beautifully.'),
('arrest', 'To take someone into custody', 'Intermediate', 'verb', '/əˈrest/', 'The police arrested the suspect.'),
('article', 'A piece of writing in a publication', 'Intermediate', 'noun', '/ˈɑː.tɪ.kəl/', 'I read an interesting article today.'),
('artificial', 'Made by humans, not natural', 'Intermediate', 'adjective', '/ˌɑː.tɪˈfɪʃ.əl/', 'Artificial flowers look real.'),

-- Advanced (50 words)
('aberration', 'A departure from what is normal', 'Advanced', 'noun', '/ˌæb.əˈreɪ.ʃən/', 'His behavior was an aberration from his usual calm demeanor.'),
('abhor', 'To regard with disgust and hatred', 'Advanced', 'verb', '/əbˈhɔːr/', 'I abhor violence of any kind.'),
('acquiesce', 'To accept reluctantly without protest', 'Advanced', 'verb', '/ˌæk.wiˈes/', 'She acquiesced to her parents'' wishes.'),
('alacrity', 'Brisk and cheerful readiness', 'Advanced', 'noun', '/əˈlæk.rə.ti/', 'He accepted the challenge with alacrity.'),
('ameliorate', 'To make something better', 'Advanced', 'verb', '/əˈmiː.li.ə.reɪt/', 'The government tried to ameliorate the housing crisis.'),
('amiable', 'Friendly and pleasant', 'Advanced', 'adjective', '/ˈeɪ.mi.ə.bəl/', 'She has an amiable personality.'),
('appease', 'To calm someone by giving them what they want', 'Advanced', 'verb', '/əˈpiːz/', 'He tried to appease the angry customer.'),
('arcane', 'Mysterious and known by few', 'Advanced', 'adjective', '/ɑːˈkeɪn/', 'The book contained arcane knowledge.'),
('avarice', 'Extreme greed for wealth', 'Advanced', 'noun', '/ˈæv.ər.ɪs/', 'His avarice led to his downfall.'),
('benevolent', 'Kind and generous', 'Advanced', 'adjective', '/bəˈnev.əl.ənt/', 'The benevolent donor gave millions to charity.'),
('brazen', 'Bold and without shame', 'Advanced', 'adjective', '/ˈbreɪ.zən/', 'It was a brazen lie.'),
('brusque', 'Abrupt in speech or manner', 'Advanced', 'adjective', '/bruːsk/', 'His brusque response surprised everyone.'),
('cajole', 'To persuade with flattery', 'Advanced', 'verb', '/kəˈdʒəʊl/', 'She cajoled him into helping her.'),
('callous', 'Showing cruel disregard for others', 'Advanced', 'adjective', '/ˈkæl.əs/', 'His callous remarks hurt her deeply.'),
('candor', 'Openness and honesty', 'Advanced', 'noun', '/ˈkæn.dər/', 'I appreciate your candor.'),
('capricious', 'Changing mood unpredictably', 'Advanced', 'adjective', '/kəˈprɪʃ.əs/', 'The capricious weather made planning difficult.'),
('chide', 'To scold or rebuke', 'Advanced', 'verb', '/tʃaɪd/', 'The teacher chided the student for being late.'),
('circumspect', 'Wary and careful', 'Advanced', 'adjective', '/ˈsɜː.kəm.spekt/', 'Be circumspect when making important decisions.'),
('clandestine', 'Kept secret, especially illicit', 'Advanced', 'adjective', '/klænˈdes.tɪn/', 'They held clandestine meetings at night.'),
('coerce', 'To force someone to do something', 'Advanced', 'verb', '/kəʊˈɜːs/', 'He was coerced into signing the document.'),
('coherent', 'Logical and consistent', 'Advanced', 'adjective', '/kəʊˈhɪə.rənt/', 'She gave a coherent explanation of the problem.'),
('complacency', 'Smug self-satisfaction', 'Advanced', 'noun', '/kəmˈpleɪ.sən.si/', 'Complacency can lead to failure.'),
('condescending', 'Acting superior to others', 'Advanced', 'adjective', '/ˌkɒn.dɪˈsen.dɪŋ/', 'His condescending tone annoyed everyone.'),
('connive', 'To conspire secretly', 'Advanced', 'verb', '/kəˈnaɪv/', 'They connived to steal the money.'),
('debilitate', 'To make weak', 'Advanced', 'verb', '/dɪˈbɪl.ɪ.teɪt/', 'The illness debilitated him for months.'),
('decry', 'To publicly denounce', 'Advanced', 'verb', '/dɪˈkraɪ/', 'Critics decried the new policy.'),
('deference', 'Humble submission and respect', 'Advanced', 'noun', '/ˈdef.ər.əns/', 'She showed deference to her elders.'),
('demure', 'Reserved and modest', 'Advanced', 'adjective', '/dɪˈmjʊər/', 'She gave a demure smile.'),
('deride', 'To ridicule or mock', 'Advanced', 'verb', '/dɪˈraɪd/', 'Critics derided his artistic choices.'),
('diligent', 'Hardworking and careful', 'Advanced', 'adjective', '/ˈdɪl.ɪ.dʒənt/', 'She is a diligent student.'),
('discern', 'To perceive or recognize', 'Advanced', 'verb', '/dɪˈsɜːn/', 'It was difficult to discern the truth.'),
('disdain', 'Contempt or scorn', 'Advanced', 'noun', '/dɪsˈdeɪn/', 'She looked at him with disdain.'),
('eloquent', 'Fluent and persuasive in speaking', 'Advanced', 'adjective', '/ˈel.ə.kwənt/', 'He gave an eloquent speech.'),
('empathy', 'Understanding others'' feelings', 'Advanced', 'noun', '/ˈem.pə.θi/', 'Empathy is important in relationships.'),
('enigma', 'Something mysterious or puzzling', 'Advanced', 'noun', '/ɪˈnɪɡ.mə/', 'Her behavior remains an enigma.'),
('ephemeral', 'Lasting for a very short time', 'Advanced', 'adjective', '/ɪˈfem.ər.əl/', 'Fame can be ephemeral.'),
('erudite', 'Having great knowledge', 'Advanced', 'adjective', '/ˈer.ʊ.daɪt/', 'The professor is an erudite scholar.'),
('exacerbate', 'To make worse', 'Advanced', 'verb', '/ɪɡˈzæs.ə.beɪt/', 'His comments exacerbated the situation.'),
('extol', 'To praise enthusiastically', 'Advanced', 'verb', '/ɪkˈstəʊl/', 'She extolled the virtues of hard work.'),
('fastidious', 'Very attentive to detail', 'Advanced', 'adjective', '/fæsˈtɪd.i.əs/', 'He is fastidious about cleanliness.'),
('furtive', 'Attempting to avoid notice', 'Advanced', 'adjective', '/ˈfɜː.tɪv/', 'She gave a furtive glance around the room.'),
('gratuitous', 'Uncalled for or unnecessary', 'Advanced', 'adjective', '/ɡrəˈtʃuː.ɪ.təs/', 'The movie had gratuitous violence.'),
('haughty', 'Arrogantly superior', 'Advanced', 'adjective', '/ˈhɔː.ti/', 'Her haughty attitude alienated her colleagues.'),
('hypocrisy', 'Claiming beliefs one doesn''t have', 'Advanced', 'noun', '/hɪˈpɒk.rə.si/', 'His hypocrisy was revealed.'),
('impeccable', 'Faultless and perfect', 'Advanced', 'adjective', '/ɪmˈpek.ə.bəl/', 'His English is impeccable.'),
('impertinent', 'Not showing proper respect', 'Advanced', 'adjective', '/ɪmˈpɜː.tɪ.nənt/', 'That was an impertinent remark.'),
('ineffable', 'Too great to be expressed in words', 'Advanced', 'adjective', '/ɪnˈef.ə.bəl/', 'She felt ineffable joy.'),
('insidious', 'Proceeding harmfully in a subtle way', 'Advanced', 'adjective', '/ɪnˈsɪd.i.əs/', 'The disease has an insidious onset.'),
('meticulous', 'Showing great attention to detail', 'Advanced', 'adjective', '/məˈtɪk.jə.ləs/', 'She is meticulous in her work.'),
('serendipity', 'Finding good things by chance', 'Advanced', 'noun', '/ˌser.ənˈdɪp.ə.ti/', 'Meeting her was pure serendipity.');
